### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'duplicate'

### ISSUE THREAD

**Issue by w1397800** [nucypher/zerodb-afgh-pre#2]
Hey @michwill, glad to learn your project again. but i have got some errors running these codes on centos 6.4 and python3.6.  here is my testcase and traceback

Testcase

from zerodb.afgh import crypto
me = crypto.Key.from_passphrase("my passphrase".encode())
bob = crypto.Key.from_passphrase("bob passphrase".encode())
bob_public_key = bob.dump_pub()
my_data = b"Hello World"
encrypted_data = me.encrypt(my_data)
re_key = me.re_key(bob.dump_pub())
rencrypted_msg = re_key.reencrypt(encrypted_data)
assert bob.decrypt_re(rencrypted_msg) == my_data

Traceback (most recent call last):
  File "/pythonProject/zerodb-afgh-test/test/test-helloworld.py", line 24, in <module>
    re_key = me.re_key(bob.dump_pub())
  File "/pythonProject/zerodb-afgh-test/zerodb/afgh/crypto/__init__.py", line 167, in re_key
    return ReKey.make(self.priv, pub)
  File "/pythonProject/zerodb-afgh-test/zerodb/afgh/crypto/__init__.py", line 181, in make
    key = AFGHProxyReEncryption.generateReEncryptionKey(pub.duplicate(), priv.duplicate())
AttributeError: 'bytes' object has no attribute 'duplicate'

**Comment by michwill** [comment]
Note that this repository is a simple wrapper around Java-based AFGH (which is not a necessarily secure implementation).

We currently work on a much more secure [pyUmbral](https://github.com/nucypher/pyUmbral) library, which I highly recommend to look at.

If you are looking to do experiments with AFGH, I'd recommend looking at [charm](https://github.com/JHUISI/charm/blob/dev/charm/schemes/prenc/pre_afgh06.py). Please note though that I wouldn't recommend using charm for any production uses.

**Comment by w1397800** [comment]
thanks for your recommendation.
